// A separate file, not a `test` key in `vite.config.ts`: that file is generated by
// Lovable and `docs/charter.md` C-9 keeps the round-trip live, so a hand edit there
// is lost on the next sync. It also wraps `@lovable.dev/vite-tanstack-config`, which
// pulls tanstackStart and nitro into whatever loads it — a test run does not want a
// server build. Vitest prefers this file over `vite.config.ts` when both exist, so
// the plugins the tests need are listed here on their own.
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  // `react` is what compiles the JSX a render test mounts. The `@/*` alias every file
  // under src/ imports with is resolved by Vite itself: `resolve.tsconfigPaths` is
  // native as of Vite 8 and warns when the `vite-tsconfig-paths` plugin that used to
  // do it here is also present. The package stays in `package.json` either way --
  // `@lovable.dev/vite-tanstack-config` declares it as a peer.
  plugins: [react()],
  resolve: { tsconfigPaths: true },
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    // `describe`, `it` and `expect` are imported, not global: one less thing the
    // tsconfig has to know about, since `include` does not list this file.
    globals: false,
    restoreMocks: true,
  },
});
