/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as DebtRouteImport } from './routes/debt'
import { Route as LearningsRouteImport } from './routes/learnings'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PoolRouteImport } from './routes/pool'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as TailRouteImport } from './routes/tail'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtRoute = DebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningsRoute = LearningsRouteImport.update({
  id: '/learnings',
  path: '/learnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRoute = PoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TailRoute = TailRouteImport.update({
  id: '/tail',
  path: '/tail',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/backlog': typeof BacklogRoute
  '/debt': typeof DebtRoute
  '/learnings': typeof LearningsRoute
  '/models': typeof ModelsRoute
  '/pool': typeof PoolRoute
  '/queue': typeof QueueRoute
  '/sessions': typeof SessionsRoute
  '/tail': typeof TailRoute
  '/tokens': typeof TokensRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/backlog': typeof BacklogRoute
  '/debt': typeof DebtRoute
  '/learnings': typeof LearningsRoute
  '/models': typeof ModelsRoute
  '/pool': typeof PoolRoute
  '/queue': typeof QueueRoute
  '/sessions': typeof SessionsRoute
  '/tail': typeof TailRoute
  '/tokens': typeof TokensRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/backlog': typeof BacklogRoute
  '/debt': typeof DebtRoute
  '/learnings': typeof LearningsRoute
  '/models': typeof ModelsRoute
  '/pool': typeof PoolRoute
  '/queue': typeof QueueRoute
  '/sessions': typeof SessionsRoute
  '/tail': typeof TailRoute
  '/tokens': typeof TokensRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/backlog'
    | '/debt'
    | '/learnings'
    | '/models'
    | '/pool'
    | '/queue'
    | '/sessions'
    | '/tail'
    | '/tokens'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/backlog'
    | '/debt'
    | '/learnings'
    | '/models'
    | '/pool'
    | '/queue'
    | '/sessions'
    | '/tail'
    | '/tokens'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/backlog'
    | '/debt'
    | '/learnings'
    | '/models'
    | '/pool'
    | '/queue'
    | '/sessions'
    | '/tail'
    | '/tokens'
    | '/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BacklogRoute: typeof BacklogRoute
  DebtRoute: typeof DebtRoute
  LearningsRoute: typeof LearningsRoute
  ModelsRoute: typeof ModelsRoute
  PoolRoute: typeof PoolRoute
  QueueRoute: typeof QueueRoute
  SessionsRoute: typeof SessionsRoute
  TailRoute: typeof TailRoute
  TokensRoute: typeof TokensRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt': {
      id: '/debt'
      path: '/debt'
      fullPath: '/debt'
      preLoaderRoute: typeof DebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learnings': {
      id: '/learnings'
      path: '/learnings'
      fullPath: '/learnings'
      preLoaderRoute: typeof LearningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tail': {
      id: '/tail'
      path: '/tail'
      fullPath: '/tail'
      preLoaderRoute: typeof TailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BacklogRoute: BacklogRoute,
  DebtRoute: DebtRoute,
  LearningsRoute: LearningsRoute,
  ModelsRoute: ModelsRoute,
  PoolRoute: PoolRoute,
  QueueRoute: QueueRoute,
  SessionsRoute: SessionsRoute,
  TailRoute: TailRoute,
  TokensRoute: TokensRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
